name: Test Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        modules: 'qtcore qtgui qtwidgets qtopengl qtnetwork qtsvg qtxml qtscript qtscripttools qtprintsupport qtdatavis3d qtxmlpatterns'
      
    - name: clone repository
      uses: actions/checkout@v2


    - name: Install Dependantcies And Make Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libgsl-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
        qmake
        make
        
        
    - name: Install Dependantcies And Make Mac
      if: startsWith(matrix.os, 'mac')
      run: |
        brew install gsl
        qmake CONFIG+=osx_dist
        make
 
